server:
  port: 5555

  #Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.shiningheart: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" #注意这里*要加引号，暴露全部，也可以只暴露相应endpoint
#  endpoint:
#    routes:
#      enabled: true # 默认为true，可以省略

zuul:
  #  prefix: /api
  routes:
    organizationservice: /organization/**
  ignored-services: 'organizationservice'

