server:
  port: 8552

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"


#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
