server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/Condurey/serviceConfig/
          searchPaths: licensingservice,organizationservice
#          username: native-cloud-apps
#          password: 0ffended

eureka:
  instance:
    preferIpAddress: true #访问的路径变为IP地址
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
